package org.sainm.psy.warning.repository

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows
import org.sainm.psy.common.exception.BizException
import org.sainm.psy.common.i18n.LocalizedMessages
import org.springframework.context.support.ReloadableResourceBundleMessageSource
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate
import org.springframework.jdbc.datasource.DriverManagerDataSource

class WarningRepositoryTest {

    private val jdbcTemplate = NamedParameterJdbcTemplate(
        DriverManagerDataSource().apply {
            setDriverClassName("org.h2.Driver")
            url = "jdbc:h2:mem:warning-repository-${System.nanoTime()};MODE=PostgreSQL;DB_CLOSE_DELAY=-1"
            username = "sa"
            password = ""
        }
    )

    private val repository = WarningRepository(jdbcTemplate, localizedMessages())

    init {
        jdbcTemplate.jdbcOperations.execute(
            """
            create table sys_user (
                id bigint primary key
            )
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            create table psy_warning_record (
                id bigint primary key,
                result_id bigint not null,
                warning_level varchar(32) not null,
                warning_priority varchar(32) not null,
                warning_reason varchar(255),
                status varchar(32) not null,
                deadline_time timestamp,
                first_response_time timestamp,
                closed_time timestamp,
                escalated_at timestamp,
                last_reminded_at timestamp,
                escalation_count int not null default 0,
                created_at timestamp not null default current_timestamp,
                updated_at timestamp not null default current_timestamp
            )
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            create table psy_warning_assignment (
                id bigint generated by default as identity primary key,
                warning_id bigint not null,
                assignee_user_id bigint not null,
                assigned_by bigint,
                assigned_at timestamp not null default current_timestamp,
                claim_time timestamp
            )
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute("insert into sys_user(id) values (10), (20), (30)")
    }

    @Test
    fun `claimWarning inserts assignment when warning is still pending`() {
        insertWarning(id = 1L, status = "PENDING")

        val result = repository.claimWarning(1L, 10L, 10L)

        assertEquals("PROCESSING", result.status)
        assertEquals(1L, countAssignments(1L))
        assertEquals("PROCESSING", warningStatus(1L))
        assertNotNull(latestClaimTime(1L))
    }

    @Test
    fun `claimWarning marks latest assigned row claimed instead of inserting another row`() {
        insertWarning(id = 2L, status = "ASSIGNED")
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_warning_assignment (warning_id, assignee_user_id, assigned_by, assigned_at, claim_time)
            values (2, 20, 30, current_timestamp, null)
            """.trimIndent()
        )

        val result = repository.claimWarning(2L, 20L, 20L)

        assertEquals("PROCESSING", result.status)
        assertEquals(1L, countAssignments(2L))
        assertEquals("PROCESSING", warningStatus(2L))
        assertNotNull(latestClaimTime(2L))
    }

    @Test
    fun `claimWarning rejects other users from claiming an assigned warning`() {
        insertWarning(id = 3L, status = "ASSIGNED")
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_warning_assignment (warning_id, assignee_user_id, assigned_by, assigned_at, claim_time)
            values (3, 20, 30, current_timestamp, null)
            """.trimIndent()
        )

        val ex = assertThrows<BizException> {
            repository.claimWarning(3L, 10L, 10L)
        }

        assertEquals("WARNING_ASSIGNED_TO_OTHER", ex.code)
        assertEquals("ASSIGNED", warningStatus(3L))
        assertEquals(1L, countAssignments(3L))
    }

    @Test
    fun `assignWarning only allows pending warnings`() {
        insertWarning(id = 4L, status = "PROCESSING")

        val ex = assertThrows<BizException> {
            repository.assignWarning(4L, 20L, 30L)
        }

        assertEquals("WARNING_ALREADY_CLAIMED", ex.code)
        assertEquals(0L, countAssignments(4L))
    }

    @Test
    fun `assignWarning inserts one assignment and moves status to assigned`() {
        insertWarning(id = 5L, status = "PENDING")

        val result = repository.assignWarning(5L, 20L, 30L)

        assertEquals("ASSIGNED", result.status)
        assertEquals("ASSIGNED", warningStatus(5L))
        assertEquals(1L, countAssignments(5L))
        assertEquals(20L, latestAssignee(5L))
    }

    private fun insertWarning(id: Long, status: String) {
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_warning_record (
                id, result_id, warning_level, warning_priority, warning_reason, status, created_at, updated_at
            ) values (
                $id, ${1000 + id}, 'HIGH', 'P1', 'test', '$status', current_timestamp, current_timestamp
            )
            """.trimIndent()
        )
    }

    private fun countAssignments(warningId: Long): Long =
        jdbcTemplate.queryForObject(
            "select count(1) from psy_warning_assignment where warning_id = :warningId",
            mapOf("warningId" to warningId),
            Long::class.java
        ) ?: 0L

    private fun warningStatus(warningId: Long): String =
        jdbcTemplate.queryForObject(
            "select status from psy_warning_record where id = :warningId",
            mapOf("warningId" to warningId),
            String::class.java
        ) ?: error("warning not found")

    private fun latestClaimTime(warningId: Long): Any? =
        jdbcTemplate.queryForObject(
            "select claim_time from psy_warning_assignment where warning_id = :warningId order by id desc limit 1",
            mapOf("warningId" to warningId),
            Any::class.java
        )

    private fun latestAssignee(warningId: Long): Long =
        jdbcTemplate.queryForObject(
            "select assignee_user_id from psy_warning_assignment where warning_id = :warningId order by id desc limit 1",
            mapOf("warningId" to warningId),
            Long::class.java
        ) ?: error("assignee not found")

    private fun localizedMessages(): LocalizedMessages {
        val messageSource = ReloadableResourceBundleMessageSource().apply {
            setBasenames("classpath:i18n/messages")
            setDefaultEncoding("UTF-8")
        }
        return LocalizedMessages(messageSource)
    }
}
