package org.sainm.psy.assessment.service

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows
import org.sainm.psy.common.i18n.LocalizedMessages
import org.springframework.context.support.ReloadableResourceBundleMessageSource
import org.springframework.context.i18n.LocaleContextHolder
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate
import org.springframework.jdbc.datasource.DriverManagerDataSource
import java.math.BigDecimal
import java.util.Locale

class ScoreCalculatorTest {

    private lateinit var jdbcTemplate: NamedParameterJdbcTemplate
    private lateinit var scoreCalculator: ScoreCalculator

    @BeforeEach
    fun setUp() {
        val dataSource = DriverManagerDataSource().apply {
            setDriverClassName("org.h2.Driver")
            url = "jdbc:h2:mem:score-calculator-${System.nanoTime()};MODE=PostgreSQL;DB_CLOSE_DELAY=-1"
            username = "sa"
            password = ""
        }
        jdbcTemplate = NamedParameterJdbcTemplate(dataSource)
        jdbcTemplate.jdbcOperations.execute(
            """
            create table psy_scale_option (
                id bigint generated by default as identity primary key,
                question_id bigint not null,
                score_value numeric(10,4) not null
            )
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            create table psy_scale_algorithm_binding (
                scale_id bigint primary key,
                algorithm_code varchar(64) not null,
                input_schema_json text
            )
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            create table psy_scale_dimension (
                id bigint generated by default as identity primary key,
                scale_id bigint not null,
                dimension_code varchar(64) not null
            )
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            create table psy_scale_result_rule (
                id bigint generated by default as identity primary key,
                scale_id bigint not null,
                dimension_id bigint null,
                risk_level varchar(32) not null,
                score_min numeric(10,2) not null,
                score_max numeric(10,2) not null,
                score_source varchar(32) not null default 'RAW_SCORE',
                norm_code varchar(64),
                result_title varchar(255),
                result_description text,
                suggestion_text text
            )
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            create table psy_scale_result_rule_translation (
                id bigint generated by default as identity primary key,
                result_rule_id bigint not null,
                locale_code varchar(16) not null,
                result_title varchar(255) not null,
                result_description text,
                suggestion_text text,
                review_status varchar(32) not null
            )
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            create table psy_scale_norm (
                id bigint generated by default as identity primary key,
                scale_id bigint not null,
                norm_code varchar(64) not null,
                dimension_id bigint null,
                applicable_target varchar(128),
                age_min int,
                age_max int,
                gender varchar(32),
                org_type varchar(64),
                mean_score numeric(10,4),
                std_deviation numeric(10,4),
                t_score_mean numeric(10,4),
                t_score_std_deviation numeric(10,4),
                sort_no int not null default 0,
                review_status varchar(32) not null default 'APPROVED'
            )
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            create table psy_scale_high_risk_rule (
                id bigint generated by default as identity primary key,
                scale_id bigint not null,
                rule_code varchar(64) not null,
                question_id bigint not null,
                option_id bigint null,
                score_threshold numeric(10,2),
                warning_level varchar(32) not null,
                result_title varchar(255),
                result_description text,
                suggestion_text text,
                sort_no int not null default 0
            )
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            create table psy_scale_high_risk_rule_translation (
                id bigint generated by default as identity primary key,
                high_risk_rule_id bigint not null,
                locale_code varchar(16) not null,
                result_title varchar(255) not null,
                result_description text,
                suggestion_text text,
                review_status varchar(32) not null
            )
            """.trimIndent()
        )
        val messageSource = ReloadableResourceBundleMessageSource().apply {
            setBasenames("classpath:i18n/messages")
            setDefaultEncoding("UTF-8")
        }
        scoreCalculator = ScoreCalculator(jdbcTemplate, LocalizedMessages(messageSource))
        LocaleContextHolder.setLocale(Locale.US)
    }

    @Test
    fun `calculate uses only approved result-rule translation for request locale`() {
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_result_rule (
                id, scale_id, dimension_id, risk_level, score_min, score_max,
                score_source, result_title, result_description, suggestion_text
            ) values (10, 1, null, 'NORMAL', 0, 10, 'RAW_SCORE', 'Base title', 'Base description', 'Base suggestion')
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_result_rule_translation (
                result_rule_id, locale_code, result_title, result_description, suggestion_text, review_status
            ) values
                (10, 'ja-JP', '日本語タイトル', '日本語説明', '日本語提案', 'APPROVED'),
                (10, 'zh-CN', '未审核标题', '未审核说明', '未审核建议', 'DRAFT')
            """.trimIndent()
        )

        LocaleContextHolder.setLocale(Locale.JAPAN)
        val japanese = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(QuestionScoreContext(1L, null, false, BigDecimal.ONE, BigDecimal.ONE))
        )
        assertEquals("日本語タイトル", japanese.resultTitle)
        assertEquals("日本語説明", japanese.resultDescription)
        assertEquals("日本語提案", japanese.suggestionText)

        LocaleContextHolder.setLocale(Locale.SIMPLIFIED_CHINESE)
        val chinese = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(QuestionScoreContext(1L, null, false, BigDecimal.ONE, BigDecimal.ONE))
        )
        assertEquals("Base title", chinese.resultTitle)
        assertEquals("Base description", chinese.resultDescription)
        assertEquals("Base suggestion", chinese.suggestionText)
    }

    @Test
    fun `SCL90 restricted algorithm emits auditable global indices`() {
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_algorithm_binding (scale_id, algorithm_code, input_schema_json)
            values (
                90,
                'SCL90_PROFILE',
                '{"restrictedProfile":{"canonicalConvention":"0_TO_4","positiveSymptomRule":"score > 0","dimensionRule":"sum(dimension item scores) / answered item count in dimension"}}'
            )
            """.trimIndent()
        )
        val result = scoreCalculator.calculate(
            scaleId = 90L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = (1..90).map { questionNo ->
                QuestionScoreContext(
                    questionNo.toLong(), 100L, false, BigDecimal.ONE,
                    when (questionNo) { 2 -> BigDecimal("2"); 3 -> BigDecimal("4"); else -> BigDecimal.ZERO }
                )
            },
            options = ScoreCalculationOptions(totalQuestionCount = 90, answeredQuestionCount = 90)
        )

        assertEquals(BigDecimal("6.0000"), result.totalScore)
        assertEquals(BigDecimal("0.0667"), result.metrics.getValue("GSI"))
        assertEquals(BigDecimal("2"), result.metrics.getValue("PST"))
        assertEquals(BigDecimal("3.0000"), result.metrics.getValue("PSDI"))
        assertEquals("SCL90_PROFILE", result.scoringTrace?.algorithmCode)
        assertEquals(result.metrics, result.scoringTrace?.derivedMetrics)
        assertEquals("0_TO_4", result.scoringTrace?.restrictedProfile?.get("canonicalConvention"))
        assertEquals("score > 0", result.scoringTrace?.restrictedProfile?.get("positiveSymptomRule"))
    }

    @Test
    fun `generic binding emits only the explicitly configured WHO5 percentage metric`() {
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_algorithm_binding (scale_id, algorithm_code, input_schema_json)
            values (5, 'GENERIC_SCORE_CALCULATOR', '{"derivedMetrics":["WHO5_PERCENTAGE_SCORE"]}')
            """.trimIndent()
        )

        val result = scoreCalculator.calculate(
            scaleId = 5L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = (1..5).map { questionNo ->
                QuestionScoreContext(
                    questionId = questionNo.toLong(),
                    dimensionId = null,
                    reverseScoreFlag = false,
                    weightValue = BigDecimal.ONE,
                    rawScore = BigDecimal(questionNo)
                )
            },
            options = ScoreCalculationOptions(totalQuestionCount = 5, answeredQuestionCount = 5)
        )

        assertEquals(BigDecimal("15.0000"), result.totalScore)
        assertEquals(BigDecimal("60.0000"), result.metrics.getValue("WHO5_PERCENTAGE_SCORE"))
        assertEquals(result.metrics, result.scoringTrace?.derivedMetrics)
    }

    @Test
    fun `calculate prorates a partial sum when the approved policy allows it`() {
        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(
                    questionId = 1L,
                    dimensionId = null,
                    reverseScoreFlag = false,
                    weightValue = BigDecimal.ONE,
                    rawScore = BigDecimal("4")
                )
            ),
            options = ScoreCalculationOptions(
                qualityPolicy = org.sainm.psy.scale.domain.ScalePackageQualityPolicy(
                    missingAnswerPolicy = "PRORATE",
                    maxMissingRatio = BigDecimal("0.5"),
                    requireAllRequiredAnswers = false
                ),
                totalQuestionCount = 2,
                answeredQuestionCount = 1,
                // SIMPLE_SUM does not apply item weights.  The prorate
                // factor must therefore use question count even when the
                // declared weights are uneven.
                totalWeight = BigDecimal("3"),
                answeredWeight = BigDecimal.ONE
            )
        )

        assertEquals(BigDecimal("8.0000"), result.totalScore)
        assertEquals("NORMAL", result.riskLevel)
    }

    @Test
    fun `weighted sum prorate uses declared weight rather than question count`() {
        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "WEIGHTED_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(
                    questionId = 1L,
                    dimensionId = null,
                    reverseScoreFlag = false,
                    weightValue = BigDecimal.ONE,
                    rawScore = BigDecimal("4")
                )
            ),
            options = ScoreCalculationOptions(
                qualityPolicy = org.sainm.psy.scale.domain.ScalePackageQualityPolicy(
                    missingAnswerPolicy = "PRORATE",
                    maxMissingRatio = BigDecimal("0.5"),
                    requireAllRequiredAnswers = false
                ),
                totalQuestionCount = 2,
                answeredQuestionCount = 1,
                totalWeight = BigDecimal("3"),
                answeredWeight = BigDecimal.ONE
            )
        )

        assertEquals(BigDecimal("12.0000"), result.totalScore)
        assertEquals(BigDecimal("3.00000000"), result.scoringTrace?.prorateFactor)
    }

    @Test
    fun `average methods use answered items for ALLOW and PRORATE without extra factor`() {
        listOf("ALLOW", "PRORATE").forEach { missingAnswerPolicy ->
            val result = scoreCalculator.calculate(
                scaleId = 1L,
                scoreMethod = "AVERAGE",
                scoreCoefficient = BigDecimal.ONE,
                items = listOf(
                    QuestionScoreContext(
                        questionId = 1L,
                        dimensionId = 10L,
                        reverseScoreFlag = false,
                        weightValue = BigDecimal.ONE,
                        rawScore = BigDecimal("4")
                    )
                ),
                options = ScoreCalculationOptions(
                    qualityPolicy = org.sainm.psy.scale.domain.ScalePackageQualityPolicy(
                        missingAnswerPolicy = missingAnswerPolicy,
                        maxMissingRatio = BigDecimal("0.5"),
                        requireAllRequiredAnswers = false
                    ),
                    totalQuestionCount = 2,
                    answeredQuestionCount = 1,
                    totalWeight = BigDecimal("3"),
                    answeredWeight = BigDecimal.ONE
                )
            )

            assertEquals(BigDecimal("4.0000"), result.totalScore)
            assertEquals(BigDecimal("4.0000"), result.dimensionScores.single().score)
            assertEquals(BigDecimal.ONE.setScale(8), result.scoringTrace?.prorateFactor)
            assertEquals(
                if (missingAnswerPolicy == "PRORATE") "PRORATED_AVERAGE" else "AVERAGE",
                result.scoringTrace?.dimensions?.single()?.aggregation
            )
        }
    }

    @Test
    fun `weighted average uses answered weight for ALLOW and PRORATE without extra factor`() {
        listOf("ALLOW", "PRORATE").forEach { missingAnswerPolicy ->
            val result = scoreCalculator.calculate(
                scaleId = 1L,
                scoreMethod = "WEIGHTED_AVERAGE",
                scoreCoefficient = BigDecimal.ONE,
                items = listOf(
                    QuestionScoreContext(
                        questionId = 1L,
                        dimensionId = 10L,
                        reverseScoreFlag = false,
                        weightValue = BigDecimal.ONE,
                        rawScore = BigDecimal("4")
                    )
                ),
                options = ScoreCalculationOptions(
                    qualityPolicy = org.sainm.psy.scale.domain.ScalePackageQualityPolicy(
                        missingAnswerPolicy = missingAnswerPolicy,
                        maxMissingRatio = BigDecimal("0.5"),
                        requireAllRequiredAnswers = false
                    ),
                    totalQuestionCount = 2,
                    answeredQuestionCount = 1,
                    totalWeight = BigDecimal("3"),
                    answeredWeight = BigDecimal.ONE
                )
            )

            assertEquals(BigDecimal("4.0000"), result.totalScore)
            assertEquals(BigDecimal("4.0000"), result.dimensionScores.single().score)
            assertEquals(BigDecimal.ONE.setScale(8), result.scoringTrace?.prorateFactor)
            assertEquals(
                if (missingAnswerPolicy == "PRORATE") "PRORATED_WEIGHTED_AVERAGE" else "WEIGHTED_AVERAGE",
                result.scoringTrace?.dimensions?.single()?.aggregation
            )
        }
    }

    @Test
    fun `calculate matches rule by z score and outputs t score`() {
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_result_rule (
                scale_id, dimension_id, risk_level, score_min, score_max, score_source, norm_code, result_title
            ) values (1, null, 'MODERATE', 1.00, 2.00, 'Z_SCORE', 'NORM_A', 'Norm matched')
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_norm (
                scale_id, norm_code, dimension_id, mean_score, std_deviation, t_score_mean, t_score_std_deviation, sort_no, review_status
            ) values (1, 'NORM_A', null, 10.0000, 2.0000, 50.0000, 10.0000, 1, 'APPROVED')
            """.trimIndent()
        )

        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(
                    questionId = 1L,
                    dimensionId = null,
                    reverseScoreFlag = false,
                    weightValue = BigDecimal.ONE,
                    rawScore = BigDecimal("12")
                )
            )
        )

        assertEquals("MODERATE", result.riskLevel)
        assertEquals("Z_SCORE", result.scoreSource)
        assertEquals(BigDecimal("1.0000"), result.standardScore)
        assertEquals(BigDecimal("1.0000"), result.zScore)
        assertEquals(BigDecimal("60.0000"), result.tScore)
        assertEquals("NORM_A", result.normCode)
    }

    @Test
    fun `unapproved norm is never selected at runtime`() {
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_result_rule (
                scale_id, dimension_id, risk_level, score_min, score_max, score_source, norm_code, result_title
            ) values (2, null, 'MODERATE', 1.00, 2.00, 'Z_SCORE', 'PENDING_NORM', 'Should not match')
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_norm (
                scale_id, norm_code, dimension_id, mean_score, std_deviation, sort_no, review_status
            ) values (2, 'PENDING_NORM', null, 10.0000, 2.0000, 1, 'PENDING_REVIEW')
            """.trimIndent()
        )

        val result = scoreCalculator.calculate(
            scaleId = 2L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(QuestionScoreContext(1L, null, false, BigDecimal.ONE, BigDecimal("12")))
        )

        assertEquals("NORMAL", result.riskLevel)
        assertEquals(null, result.normCode)
        assertFalse(result.resultRuleMatched)
    }

    @Test
    fun `calculate elevates result when high risk rule is triggered`() {
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_high_risk_rule (
                scale_id, rule_code, question_id, option_id, warning_level, result_title, result_description, suggestion_text, sort_no
            ) values (1, 'HR_1', 1, 99, 'HIGH', 'Critical alert', 'High risk item matched', 'Immediate follow-up required', 1)
            """.trimIndent()
        )

        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(
                    questionId = 1L,
                    dimensionId = null,
                    reverseScoreFlag = false,
                    weightValue = BigDecimal.ONE,
                    rawScore = BigDecimal.ZERO,
                    selectedOptionIds = listOf(99L)
                )
            )
        )

        assertTrue(result.highRiskTriggered)
        assertEquals("HR_1", result.highRiskRuleCode)
        assertEquals("HIGH", result.highRiskWarningLevel)
        assertEquals("HIGH", result.riskLevel)
        assertEquals("Critical alert", result.resultTitle)
    }

    @Test
    fun `calculate uses approved high-risk translation for explicit response locale`() {
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_high_risk_rule (
                id, scale_id, rule_code, question_id, option_id, warning_level,
                result_title, result_description, suggestion_text, sort_no
            ) values (21, 1, 'HR_JA', 1, 99, 'HIGH', 'Base alert', 'Base description', 'Base suggestion', 1)
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_high_risk_rule_translation (
                high_risk_rule_id, locale_code, result_title, result_description, suggestion_text, review_status
            ) values
                (21, 'ja-JP', '緊急フォロー', '高リスク項目に該当しました', '担当者が直ちに確認してください', 'APPROVED'),
                (21, 'zh-CN', '未审核', '未审核', '未审核', 'DRAFT')
            """.trimIndent()
        )

        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(QuestionScoreContext(1L, null, false, BigDecimal.ONE, BigDecimal.ZERO, listOf(99L))),
            localeCode = "ja-JP"
        )

        assertEquals("緊急フォロー", result.resultTitle)
        assertEquals("高リスク項目に該当しました", result.resultDescription)
        assertEquals("担当者が直ちに確認してください", result.suggestionText)
    }

    @Test
    fun `calculate treats attention as a moderate risk instead of normal`() {
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_high_risk_rule (
                scale_id, rule_code, question_id, option_id, warning_level, sort_no
            ) values (1, 'ATTENTION_1', 1, 99, 'ATTENTION', 1)
            """.trimIndent()
        )

        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(
                    questionId = 1L,
                    dimensionId = null,
                    reverseScoreFlag = false,
                    weightValue = BigDecimal.ONE,
                    rawScore = BigDecimal.ZERO,
                    selectedOptionIds = listOf(99L)
                )
            )
        )

        assertEquals("ATTENTION", result.riskLevel)
        assertEquals("ATTENTION", result.highRiskWarningLevel)
    }

    @Test
    fun `calculate ignores dormant high risk rules when scale switch is disabled`() {
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_high_risk_rule (
                scale_id, rule_code, question_id, option_id, warning_level, sort_no
            ) values (1, 'DORMANT', 1, 99, 'HIGH', 1)
            """.trimIndent()
        )

        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(
                    questionId = 1L,
                    dimensionId = null,
                    reverseScoreFlag = false,
                    weightValue = BigDecimal.ONE,
                    rawScore = BigDecimal.ZERO,
                    selectedOptionIds = listOf(99L)
                )
            ),
            highRiskWarningEnabled = false
        )

        assertFalse(result.highRiskTriggered)
        assertEquals("NORMAL", result.riskLevel)
    }

    @Test
    fun `calculate auto matches layered norm by user profile`() {
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_result_rule (
                scale_id, dimension_id, risk_level, score_min, score_max, score_source, result_title
            ) values (1, null, 'LOW', 49.00, 51.00, 'T_SCORE', 'Layered norm matched')
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_norm (
                scale_id, norm_code, dimension_id, applicable_target, age_min, age_max, gender, org_type,
                mean_score, std_deviation, t_score_mean, t_score_std_deviation, sort_no
            ) values (1, 'AUTO_STUDENT', null, 'student', 18, 25, 'FEMALE', 'school', 10.0000, 2.0000, 50.0000, 10.0000, 1)
            """.trimIndent()
        )

        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(
                    questionId = 1L,
                    dimensionId = null,
                    reverseScoreFlag = false,
                    weightValue = BigDecimal.ONE,
                    rawScore = BigDecimal("10")
                )
            ),
            normContext = NormMatchingContext(
                age = 20,
                gender = "FEMALE",
                orgType = "school",
                applicableTarget = "student",
                preferredNormCode = null
            )
        )

        assertEquals("LOW", result.riskLevel)
        assertEquals("AUTO_STUDENT", result.normCode)
        assertEquals(BigDecimal("50.0000"), result.tScore)
        assertTrue(result.scoringTrace?.normSelectionReason?.contains("specificity=") == true)
    }

    @Test
    fun `weighted scoring composes reverse recoding and question weight`() {
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_option (question_id, score_value)
            values (11, 0), (11, 3)
            """.trimIndent()
        )

        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "WEIGHTED_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(
                    questionId = 11L,
                    dimensionId = null,
                    reverseScoreFlag = true,
                    weightValue = BigDecimal("2"),
                    rawScore = BigDecimal("1")
                )
            )
        )

        assertEquals(BigDecimal("4.0000"), result.totalScore)
        assertEquals("GENERIC_SCORE_CALCULATOR", result.scoringTrace?.algorithmCode)
        assertEquals("1", result.scoringTrace?.algorithmVersion)
        assertEquals(BigDecimal("1"), result.scoringTrace?.questions?.single()?.rawScore)
        assertEquals(BigDecimal("2.0000"), result.scoringTrace?.questions?.single()?.reverseScore)
        assertEquals(BigDecimal("4.0000"), result.scoringTrace?.questions?.single()?.weightedScore)
    }

    @Test
    fun `unsupported scoring method fails instead of silently falling back`() {
        val error = assertThrows<IllegalArgumentException> {
            scoreCalculator.calculate(
                scaleId = 1L,
                scoreMethod = "CUSTOM_UNKNOWN",
                scoreCoefficient = BigDecimal.ONE,
                items = listOf(
                    QuestionScoreContext(
                        questionId = 1L,
                        dimensionId = null,
                        reverseScoreFlag = false,
                        weightValue = BigDecimal.ONE,
                        rawScore = BigDecimal.ONE
                    )
                )
            )
        }

        assertTrue(error.message!!.contains("CUSTOM_UNKNOWN"))
    }

    @Test
    fun `average and weighted average support common scale aggregation`() {
        val average = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "AVERAGE",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(1L, null, false, BigDecimal.ONE, BigDecimal("1")),
                QuestionScoreContext(2L, null, false, BigDecimal.ONE, BigDecimal("3"))
            )
        )
        val weightedAverage = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "WEIGHTED_AVERAGE",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(1L, null, false, BigDecimal("1"), BigDecimal("1")),
                QuestionScoreContext(2L, null, false, BigDecimal("3"), BigDecimal("3"))
            )
        )

        assertEquals(BigDecimal("2.0000"), average.totalScore)
        assertEquals(BigDecimal("2.5000"), weightedAverage.totalScore)
    }

    @Test
    fun `simple sum dimension score is a sum rather than an average`() {
        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(1L, 10L, false, BigDecimal.ONE, BigDecimal("2")),
                QuestionScoreContext(2L, 10L, false, BigDecimal.ONE, BigDecimal("3"))
            )
        )

        assertEquals(BigDecimal("5.0000"), result.dimensionScores.single().score)
        assertEquals("SUM", result.scoringTrace?.dimensions?.single()?.aggregation)
    }

    @Test
    fun `dimension aggregation can differ from the global total aggregation`() {
        jdbcTemplate.jdbcOperations.execute(
            "insert into psy_scale_algorithm_binding (scale_id, algorithm_code, input_schema_json) " +
                "values (1, 'GENERIC_SCORE_CALCULATOR', '{\"dimensionAggregation\":\"AVERAGE\"}')"
        )
        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(1L, 10L, false, BigDecimal.ONE, BigDecimal("2")),
                QuestionScoreContext(2L, 10L, false, BigDecimal.ONE, BigDecimal("3"))
            )
        )

        assertEquals(BigDecimal("5.0000"), result.totalScore)
        assertEquals(BigDecimal("2.5000"), result.dimensionScores.single().score)
        assertEquals("AVERAGE", result.scoringTrace?.dimensions?.single()?.aggregation)
    }

    @Test
    fun `weighted dimension prorate uses declared dimension weight total`() {
        jdbcTemplate.jdbcOperations.execute(
            "insert into psy_scale_algorithm_binding (scale_id, algorithm_code, input_schema_json) " +
                "values (17, 'GENERIC_SCORE_CALCULATOR', '{\"dimensionAggregation\":\"WEIGHTED_SUM\"}')"
        )

        val result = scoreCalculator.calculate(
            scaleId = 17L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(
                    questionId = 1L,
                    dimensionId = 10L,
                    reverseScoreFlag = false,
                    weightValue = BigDecimal.ONE,
                    rawScore = BigDecimal("4"),
                    dimensionQuestionCount = 2,
                    dimensionWeightTotal = BigDecimal("3")
                )
            ),
            options = ScoreCalculationOptions(
                qualityPolicy = org.sainm.psy.scale.domain.ScalePackageQualityPolicy(
                    missingAnswerPolicy = "PRORATE",
                    maxMissingRatio = BigDecimal("0.5"),
                    requireAllRequiredAnswers = false
                ),
                totalQuestionCount = 1,
                answeredQuestionCount = 1
            )
        )

        assertEquals(BigDecimal("4.0000"), result.totalScore)
        assertEquals(BigDecimal("12.0000"), result.dimensionScores.single().score)
        assertEquals("PRORATED_SUM", result.scoringTrace?.dimensions?.single()?.aggregation)
    }

    @Test
    fun `average dimension score uses average aggregation`() {
        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "AVERAGE",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(1L, 10L, false, BigDecimal.ONE, BigDecimal("2")),
                QuestionScoreContext(2L, 10L, false, BigDecimal.ONE, BigDecimal("3"))
            )
        )

        assertEquals(BigDecimal("2.5000"), result.dimensionScores.single().score)
        assertEquals("AVERAGE", result.scoringTrace?.dimensions?.single()?.aggregation)
    }

    @Test
    fun `dimension recode maps aggregate sum into declared bands`() {
        jdbcTemplate.jdbcOperations.execute(
            "insert into psy_scale_dimension (id, scale_id, dimension_code) values (10, 1, 'D1')"
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_algorithm_binding (scale_id, algorithm_code, input_schema_json) values (
                1, 'GENERIC_SCORE_CALCULATOR',
                '{"dimensionRecodes":{"D1":{"rule":"RECODE_SUM_TO_0_3","bands":[{"min":0,"max":1,"value":0},{"min":2,"max":3,"value":1},{"min":4,"max":5,"value":2},{"min":6,"max":100,"value":3}]}}}'
            )
            """.trimIndent()
        )

        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(1L, 10L, false, BigDecimal.ONE, BigDecimal("2")),
                QuestionScoreContext(2L, 10L, false, BigDecimal.ONE, BigDecimal("3"))
            )
        )

        assertEquals(BigDecimal("2"), result.dimensionScores.single().score)
    }

    @Test
    fun `sleep duration recode computes cross-midnight duration and maps it`() {
        jdbcTemplate.jdbcOperations.execute(
            "insert into psy_scale_dimension (id, scale_id, dimension_code) values (10, 1, 'D1')"
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_algorithm_binding (scale_id, algorithm_code, input_schema_json) values (
                1, 'GENERIC_SCORE_CALCULATOR',
                '{"dimensionRecodes":{"D1":{"rule":"SLEEP_DURATION_RECODE_0_3","startQuestionId":1,"endQuestionId":2,"bands":[{"min":0,"max":360,"value":3},{"min":361,"max":420,"value":2},{"min":421,"max":480,"value":1},{"min":481,"max":99999,"value":0}]}}}'
            )
            """.trimIndent()
        )

        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(1L, 10L, false, BigDecimal.ONE, BigDecimal.ZERO, answerText = "23:30"),
                QuestionScoreContext(2L, 10L, false, BigDecimal.ONE, BigDecimal.ZERO, answerText = "07:00")
            )
        )

        assertEquals(BigDecimal("1"), result.dimensionScores.single().score)
    }

    @Test
    fun `sleep efficiency recode computes efficiency percentage and maps it`() {
        jdbcTemplate.jdbcOperations.execute(
            "insert into psy_scale_dimension (id, scale_id, dimension_code) values (10, 1, 'D1')"
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_algorithm_binding (scale_id, algorithm_code, input_schema_json) values (
                1, 'GENERIC_SCORE_CALCULATOR',
                '{"dimensionRecodes":{"D1":{"rule":"SLEEP_EFFICIENCY_RECODE_0_3","startQuestionId":1,"endQuestionId":2,"sleepQuestionId":3,"bands":[{"min":0,"max":64,"value":3},{"min":65,"max":74,"value":2},{"min":75,"max":84,"value":1},{"min":85,"max":100,"value":0}]}}}'
            )
            """.trimIndent()
        )

        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(1L, 10L, false, BigDecimal.ONE, BigDecimal.ZERO, answerText = "23:30"),
                QuestionScoreContext(2L, 10L, false, BigDecimal.ONE, BigDecimal.ZERO, answerText = "07:00"),
                QuestionScoreContext(3L, 10L, false, BigDecimal.ONE, BigDecimal.ZERO, answerValue = BigDecimal(360))
            )
        )

        assertEquals(BigDecimal("1"), result.dimensionScores.single().score)
    }

    @Test
    fun `calculator rejects malformed scoring contexts instead of producing a trace`() {
        val duplicateError = assertThrows<IllegalArgumentException> {
            scoreCalculator.calculate(
                scaleId = 1L,
                scoreMethod = "SIMPLE_SUM",
                scoreCoefficient = BigDecimal.ONE,
                items = listOf(
                    QuestionScoreContext(1L, null, false, BigDecimal.ONE, BigDecimal.ONE),
                    QuestionScoreContext(1L, null, false, BigDecimal.ONE, BigDecimal.ONE)
                )
            )
        }
        assertTrue(duplicateError.message!!.contains("Duplicate question contexts"))

        val weightError = assertThrows<IllegalArgumentException> {
            scoreCalculator.calculate(
                scaleId = 1L,
                scoreMethod = "SIMPLE_SUM",
                scoreCoefficient = BigDecimal.ONE,
                items = listOf(QuestionScoreContext(1L, null, false, BigDecimal.ZERO, BigDecimal.ONE))
            )
        }
        assertTrue(weightError.message!!.contains("weights must be positive"))

        val policyError = assertThrows<IllegalArgumentException> {
            scoreCalculator.calculate(
                scaleId = 1L,
                scoreMethod = "SIMPLE_SUM",
                scoreCoefficient = BigDecimal.ONE,
                items = listOf(QuestionScoreContext(1L, null, false, BigDecimal.ONE, BigDecimal.ONE)),
                options = ScoreCalculationOptions(
                    qualityPolicy = org.sainm.psy.scale.domain.ScalePackageQualityPolicy(
                        missingAnswerPolicy = "PENDING_PROFESSIONAL_REVIEW"
                    )
                )
            )
        }
        assertTrue(policyError.message!!.contains("Unsupported missing answer policy"))
    }
}
