package org.sainm.psy.assessment.service

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.assertThrows
import org.sainm.psy.common.i18n.LocalizedMessages
import org.springframework.context.support.ReloadableResourceBundleMessageSource
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate
import org.springframework.jdbc.datasource.DriverManagerDataSource
import java.math.BigDecimal

class ScoreCalculatorTest {

    private lateinit var jdbcTemplate: NamedParameterJdbcTemplate
    private lateinit var scoreCalculator: ScoreCalculator

    @BeforeEach
    fun setUp() {
        val dataSource = DriverManagerDataSource().apply {
            setDriverClassName("org.h2.Driver")
            url = "jdbc:h2:mem:score-calculator-${System.nanoTime()};MODE=PostgreSQL;DB_CLOSE_DELAY=-1"
            username = "sa"
            password = ""
        }
        jdbcTemplate = NamedParameterJdbcTemplate(dataSource)
        jdbcTemplate.jdbcOperations.execute(
            """
            create table psy_scale_option (
                id bigint generated by default as identity primary key,
                question_id bigint not null,
                score_value numeric(10,4) not null
            )
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            create table psy_scale_result_rule (
                id bigint generated by default as identity primary key,
                scale_id bigint not null,
                dimension_id bigint null,
                risk_level varchar(32) not null,
                score_min numeric(10,2) not null,
                score_max numeric(10,2) not null,
                score_source varchar(32) not null default 'RAW_SCORE',
                norm_code varchar(64),
                result_title varchar(255),
                result_description text,
                suggestion_text text
            )
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            create table psy_scale_norm (
                id bigint generated by default as identity primary key,
                scale_id bigint not null,
                norm_code varchar(64) not null,
                dimension_id bigint null,
                applicable_target varchar(128),
                age_min int,
                age_max int,
                gender varchar(32),
                org_type varchar(64),
                mean_score numeric(10,4),
                std_deviation numeric(10,4),
                t_score_mean numeric(10,4),
                t_score_std_deviation numeric(10,4),
                sort_no int not null default 0
            )
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            create table psy_scale_high_risk_rule (
                id bigint generated by default as identity primary key,
                scale_id bigint not null,
                rule_code varchar(64) not null,
                question_id bigint not null,
                option_id bigint null,
                score_threshold numeric(10,2),
                warning_level varchar(32) not null,
                result_title varchar(255),
                result_description text,
                suggestion_text text,
                sort_no int not null default 0
            )
            """.trimIndent()
        )
        val messageSource = ReloadableResourceBundleMessageSource().apply {
            setBasenames("classpath:i18n/messages")
            setDefaultEncoding("UTF-8")
        }
        scoreCalculator = ScoreCalculator(jdbcTemplate, LocalizedMessages(messageSource))
    }

    @Test
    fun `calculate matches rule by z score and outputs t score`() {
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_result_rule (
                scale_id, dimension_id, risk_level, score_min, score_max, score_source, norm_code, result_title
            ) values (1, null, 'MODERATE', 1.00, 2.00, 'Z_SCORE', 'NORM_A', 'Norm matched')
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_norm (
                scale_id, norm_code, dimension_id, mean_score, std_deviation, t_score_mean, t_score_std_deviation, sort_no
            ) values (1, 'NORM_A', null, 10.0000, 2.0000, 50.0000, 10.0000, 1)
            """.trimIndent()
        )

        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(
                    questionId = 1L,
                    dimensionId = null,
                    reverseScoreFlag = false,
                    weightValue = BigDecimal.ONE,
                    rawScore = BigDecimal("12")
                )
            )
        )

        assertEquals("MODERATE", result.riskLevel)
        assertEquals("Z_SCORE", result.scoreSource)
        assertEquals(BigDecimal("1.0000"), result.standardScore)
        assertEquals(BigDecimal("1.0000"), result.zScore)
        assertEquals(BigDecimal("60.0000"), result.tScore)
        assertEquals("NORM_A", result.normCode)
    }

    @Test
    fun `calculate elevates result when high risk rule is triggered`() {
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_high_risk_rule (
                scale_id, rule_code, question_id, option_id, warning_level, result_title, result_description, suggestion_text, sort_no
            ) values (1, 'HR_1', 1, 99, 'HIGH', 'Critical alert', 'High risk item matched', 'Immediate follow-up required', 1)
            """.trimIndent()
        )

        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(
                    questionId = 1L,
                    dimensionId = null,
                    reverseScoreFlag = false,
                    weightValue = BigDecimal.ONE,
                    rawScore = BigDecimal.ZERO,
                    selectedOptionIds = listOf(99L)
                )
            )
        )

        assertTrue(result.highRiskTriggered)
        assertEquals("HR_1", result.highRiskRuleCode)
        assertEquals("HIGH", result.highRiskWarningLevel)
        assertEquals("HIGH", result.riskLevel)
        assertEquals("Critical alert", result.resultTitle)
    }

    @Test
    fun `calculate auto matches layered norm by user profile`() {
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_result_rule (
                scale_id, dimension_id, risk_level, score_min, score_max, score_source, result_title
            ) values (1, null, 'LOW', 49.00, 51.00, 'T_SCORE', 'Layered norm matched')
            """.trimIndent()
        )
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_norm (
                scale_id, norm_code, dimension_id, applicable_target, age_min, age_max, gender, org_type,
                mean_score, std_deviation, t_score_mean, t_score_std_deviation, sort_no
            ) values (1, 'AUTO_STUDENT', null, 'student', 18, 25, 'FEMALE', 'school', 10.0000, 2.0000, 50.0000, 10.0000, 1)
            """.trimIndent()
        )

        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "SIMPLE_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(
                    questionId = 1L,
                    dimensionId = null,
                    reverseScoreFlag = false,
                    weightValue = BigDecimal.ONE,
                    rawScore = BigDecimal("10")
                )
            ),
            normContext = NormMatchingContext(
                age = 20,
                gender = "FEMALE",
                orgType = "school",
                applicableTarget = "student",
                preferredNormCode = null
            )
        )

        assertEquals("LOW", result.riskLevel)
        assertEquals("AUTO_STUDENT", result.normCode)
        assertEquals(BigDecimal("50.0000"), result.tScore)
    }

    @Test
    fun `weighted scoring composes reverse recoding and question weight`() {
        jdbcTemplate.jdbcOperations.execute(
            """
            insert into psy_scale_option (question_id, score_value)
            values (11, 0), (11, 3)
            """.trimIndent()
        )

        val result = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "WEIGHTED_SUM",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(
                    questionId = 11L,
                    dimensionId = null,
                    reverseScoreFlag = true,
                    weightValue = BigDecimal("2"),
                    rawScore = BigDecimal("1")
                )
            )
        )

        assertEquals(BigDecimal("4.0000"), result.totalScore)
    }

    @Test
    fun `unsupported scoring method fails instead of silently falling back`() {
        val error = assertThrows<IllegalArgumentException> {
            scoreCalculator.calculate(
                scaleId = 1L,
                scoreMethod = "CUSTOM_UNKNOWN",
                scoreCoefficient = BigDecimal.ONE,
                items = listOf(
                    QuestionScoreContext(
                        questionId = 1L,
                        dimensionId = null,
                        reverseScoreFlag = false,
                        weightValue = BigDecimal.ONE,
                        rawScore = BigDecimal.ONE
                    )
                )
            )
        }

        assertTrue(error.message!!.contains("CUSTOM_UNKNOWN"))
    }

    @Test
    fun `average and weighted average support common scale aggregation`() {
        val average = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "AVERAGE",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(1L, null, false, BigDecimal.ONE, BigDecimal("1")),
                QuestionScoreContext(2L, null, false, BigDecimal.ONE, BigDecimal("3"))
            )
        )
        val weightedAverage = scoreCalculator.calculate(
            scaleId = 1L,
            scoreMethod = "WEIGHTED_AVERAGE",
            scoreCoefficient = BigDecimal.ONE,
            items = listOf(
                QuestionScoreContext(1L, null, false, BigDecimal("1"), BigDecimal("1")),
                QuestionScoreContext(2L, null, false, BigDecimal("3"), BigDecimal("3"))
            )
        )

        assertEquals(BigDecimal("2.0000"), average.totalScore)
        assertEquals(BigDecimal("2.5000"), weightedAverage.totalScore)
    }
}
