import { expect, test, type APIRequestContext, type APIResponse, type Page } from "@playwright/test";

const TEST_PASSWORD = process.env.PSY_E2E_PASSWORD ?? "ChangeMe123";

type LoginData = { accessToken: string; refreshToken: string; expiresIn: number };
type ApiEnvelope<T> = { code: string; message: string; data: T };
type ScaleDetail = {
  id: number;
  scaleCode: string;
  versionNo: string;
  questions: Array<{
    id: number;
    dimensionId?: number | null;
    questionNo: number;
    questionTitle: string;
    requiredFlag: boolean;
    reverseScoreFlag: boolean;
    weightValue: number;
    sortNo: number;
  }>;
};
type ScalePackage = {
  scaleId: number;
  translations: Array<Record<string, unknown>>;
  dimensionTranslations: Array<Record<string, unknown>>;
  questionTranslations: Array<Record<string, unknown>>;
  optionTranslations: Array<Record<string, unknown>>;
  resultRuleTranslations: Array<Record<string, unknown>>;
  highRiskRuleTranslations: Array<Record<string, unknown>>;
};

async function login(request: APIRequestContext, principal: string): Promise<LoginData> {
  const response = await request.post("/auth/login/password", {
    data: {
      principal,
      password: TEST_PASSWORD,
      deviceId: `playwright-publication-${principal}`,
      deviceType: "WEB",
      deviceName: "Scale publication closure E2E"
    },
    headers: { "Accept-Language": "en-US" }
  });
  expect(response.status(), await response.text()).toBe(200);
  return (await response.json() as ApiEnvelope<LoginData>).data;
}

function authHeaders(loginData: LoginData) {
  return { Authorization: `Bearer ${loginData.accessToken}`, "Accept-Language": "en-US" };
}

async function installBrowserSession(page: Page, loginData: LoginData) {
  await page.goto("/login");
  await page.evaluate(({ accessToken, refreshToken, expiresIn }) => {
    window.localStorage.clear();
    window.sessionStorage.clear();
    window.localStorage.setItem("psy-admin-web.auth-token", accessToken);
    window.localStorage.setItem("psy-admin-web.refresh-token", refreshToken);
    window.localStorage.setItem("psy-admin-web.access-token-expires-at", String(Date.now() + expiresIn * 1000));
    window.localStorage.setItem("psy-admin-web.locale", "en-US");
  }, loginData);
}

async function expectOk<T>(response: APIResponse): Promise<T> {
  expect(response.status(), await response.text()).toBe(200);
  return (await response.json() as ApiEnvelope<T>).data;
}

function approveTranslations(items: Array<Record<string, unknown>>) {
  return items.map((item) => ({ ...item, reviewStatus: "APPROVED" }));
}

function approvedPackagePayload(pkg: ScalePackage) {
  return {
    governance: {
      sourceTitle: "Repository-owned E2E synthetic fixture",
      publisherName: "lx-boot test suite",
      manualVersion: "e2e-1",
      citationText: "Generated by the repository E2E fixture; no clinical or normative claim.",
      copyrightStatus: "AUTHORIZED",
      rightsHolder: "lx-boot test fixture",
      authorizationStatus: "AUTHORIZED",
      authorizationType: "INTERNAL_TEST_ONLY",
      authorizationScope: "Disposable isolated browser automation only",
      authorizedTerritories: "Disposable local and CI environments",
      authorizedLanguages: "zh-CN,ja-JP,en",
      targetPopulation: "Synthetic test identities only",
      exclusionCriteria: "All real respondents and every clinical use",
      estimatedMinutes: 1,
      resultVisibility: "Test automation only",
      dataUsageStatement: "Disposable synthetic data",
      nonDiagnosticStatement: "This synthetic fixture is not a diagnosis and has no clinical meaning.",
      helpResourceText: "Use only the controlled E2E workflow.",
      governanceStatus: "APPROVED"
    },
    translations: approveTranslations(pkg.translations),
    dimensionTranslations: approveTranslations(pkg.dimensionTranslations),
    questionTranslations: approveTranslations(pkg.questionTranslations),
    optionTranslations: approveTranslations(pkg.optionTranslations),
    resultRuleTranslations: approveTranslations(pkg.resultRuleTranslations),
    highRiskRuleTranslations: approveTranslations(pkg.highRiskRuleTranslations),
    qualityPolicy: {
      missingAnswerPolicy: "REJECT",
      maxMissingRatio: 0,
      minimumDurationSeconds: null,
      maximumDurationSeconds: null,
      invalidResultAction: "INVALIDATE",
      requireAllRequiredAnswers: true
    },
    validityRules: [],
    algorithmBinding: {
      algorithmCode: "GENERIC_SCORE_CALCULATOR",
      algorithmVersion: "1",
      implementationType: "BUILTIN",
      inputSchemaJson: "{}",
      outputSchemaJson: "{}",
      implementationChecksum: null,
      reviewStatus: "APPROVED"
    },
    normGovernance: []
  };
}

function buildGoldenCases(suffix: string) {
  return [
    {
      caseCode: `NORMAL_${suffix}`, caseType: "NORMAL",
      input: { answers: [{ questionNo: 1, optionCodes: ["A"] }, { questionNo: 2, optionCodes: ["A"] }, { questionNo: 3, optionCodes: ["A"] }] },
      expected: { valid: true, totalScore: 6, riskLevel: "MEDIUM", highRiskTriggered: false, dimensions: {} }
    },
    {
      caseCode: `BOUNDARY_${suffix}`, caseType: "BOUNDARY",
      input: { answers: [{ questionNo: 1, optionCodes: ["A"] }, { questionNo: 2, optionCodes: ["A"] }, { questionNo: 3, optionCodes: ["D"] }] },
      expected: { valid: true, totalScore: 3, riskLevel: "HIGH", highRiskTriggered: true, highRiskRuleCode: "E2E_HIGH_OPTION", dimensions: {} }
    },
    {
      caseCode: `REVERSE_${suffix}`, caseType: "REVERSE",
      input: { answers: [{ questionNo: 1, optionCodes: ["D"] }, { questionNo: 2, optionCodes: ["D"] }, { questionNo: 3, optionCodes: ["A"] }] },
      expected: { valid: true, totalScore: 12, riskLevel: "HIGH", highRiskTriggered: false, dimensions: {} }
    },
    {
      caseCode: `MISSING_${suffix}`, caseType: "MISSING",
      input: { answers: [{ questionNo: 1, optionCodes: ["A"] }, { questionNo: 2, optionCodes: ["A"] }] },
      expected: { valid: false, errorCode: "MISSING_REQUIRED_ANSWER", dimensions: {} }
    },
    {
      caseCode: `INVALID_${suffix}`, caseType: "INVALID",
      input: { answers: [{ questionNo: 1, optionCodes: ["Z"] }, { questionNo: 2, optionCodes: ["A"] }, { questionNo: 3, optionCodes: ["A"] }] },
      expected: { valid: false, errorCode: "OPTION_NOT_FOUND", dimensions: {} }
    },
    {
      caseCode: `HIGH_RISK_${suffix}`, caseType: "HIGH_RISK",
      input: { answers: [{ questionNo: 1, optionCodes: ["A"] }, { questionNo: 2, optionCodes: ["A"] }, { questionNo: 3, optionCodes: ["D"] }] },
      expected: { valid: true, totalScore: 3, riskLevel: "HIGH", highRiskTriggered: true, highRiskRuleCode: "E2E_HIGH_OPTION", dimensions: {} }
    }
  ];
}

test("Golden Cases and independent reviews publish one immutable scale version that a task locks", async ({ page, request }) => {
  test.setTimeout(120_000);
  const consoleErrors: string[] = [];
  page.on("console", (message) => {
    if (message.type() === "error") consoleErrors.push(message.text());
  });
  page.on("pageerror", (error) => consoleErrors.push(error.message));

  const systemAdmin = await login(request, "e2e_admin");
  const counselor = await login(request, "counselor");
  const assessor = await login(request, "assessor");
  const campusAssessor = await login(request, "campus_assessor");
  const suffix = `${Date.now()}-${test.info().workerIndex}`;

  const sourcePage = await expectOk<{ list: Array<{ id: number; scaleCode: string }> }>(
    await request.get("/api/v1/scales?scaleName=E2E%20Core%20Risk%20Technical%20Fixture&page=1&size=20", {
      headers: authHeaders(systemAdmin)
    })
  );
  const sourceScale = sourcePage.list.find((scale) => scale.scaleCode === "E2E_CORE_TECH_FIXTURE");
  expect(sourceScale).toBeDefined();

  const version = await expectOk<{ id: number; versionNo: string }>(
    await request.post(`/api/v1/scales/${sourceScale!.id}/versions`, {
      headers: authHeaders(systemAdmin),
      data: {
        versionNo: `gov-${suffix}`,
        scaleName: `E2E Governance Technical Fixture ${suffix}`,
        description: "Repository-owned synthetic test content. Not a validated psychological scale and not for clinical use."
      }
    })
  );
  const scaleId = version.id;
  const detail = await expectOk<ScaleDetail>(
    await request.get(`/api/v1/scales/${scaleId}`, { headers: authHeaders(systemAdmin) })
  );
  const reverseQuestion = detail.questions.find((question) => question.questionNo === 3);
  expect(reverseQuestion).toBeDefined();
  await expectOk<ScaleDetail>(
    await request.post(`/api/v1/scales/${scaleId}/questions/${reverseQuestion!.id}`, {
      headers: authHeaders(systemAdmin),
      data: {
        dimensionId: reverseQuestion!.dimensionId,
        questionTitle: reverseQuestion!.questionTitle,
        requiredFlag: reverseQuestion!.requiredFlag,
        reverseScoreFlag: true,
        weightValue: reverseQuestion!.weightValue,
        sortNo: reverseQuestion!.sortNo
      }
    })
  );

  const pkg = await expectOk<ScalePackage>(
    await request.get(`/api/v1/scales/${scaleId}/package`, { headers: authHeaders(systemAdmin) })
  );
  const packageResponse = await request.put(`/api/v1/scales/${scaleId}/package`, {
    headers: authHeaders(systemAdmin),
    data: approvedPackagePayload(pkg)
  });
  expect(packageResponse.status(), await packageResponse.text()).toBe(200);

  const cases = buildGoldenCases(suffix);
  for (const goldenCase of cases) {
    const response = await request.post(`/api/v1/scales/${scaleId}/publication/golden-cases`, {
      headers: authHeaders(systemAdmin),
      data: {
        ...goldenCase,
        sourceReference: "Repository-owned synthetic expected result; no clinical meaning."
      }
    });
    expect(response.status(), `${goldenCase.caseType}: ${await response.text()}`).toBe(200);
  }

  const crossTenantReadiness = await request.get(`/api/v1/scales/${scaleId}/publication/readiness`, {
    headers: authHeaders(campusAssessor)
  });
  expect(crossTenantReadiness.status()).toBe(404);
  expect((await crossTenantReadiness.json() as ApiEnvelope<null>).code).toBe("SCALE_NOT_FOUND");

  await installBrowserSession(page, systemAdmin);
  await page.goto(`/scale-publication?scaleId=${scaleId}`);
  await expect(page.getByRole("heading", { name: "Scale Publication Readiness and Review" })).toBeVisible();
  const goldenCasesTable = page.locator(".ant-card").filter({
    has: page.locator(".ant-card-head-title").getByText("Golden Case evidence", { exact: true })
  }).getByRole("table").first();
  for (const goldenCase of cases) {
    const row = goldenCasesTable.getByRole("row").filter({ hasText: goldenCase.caseCode });
    await row.getByRole("button", { name: "Run", exact: true }).click();
    const evidence = page.getByRole("dialog", { name: "Golden Case run evidence" });
    await expect(evidence.getByText("Passed", { exact: true })).toBeVisible();
    await evidence.locator("button.ant-modal-close").click();
    await expect(evidence).toBeHidden();
    const refreshedRow = goldenCasesTable.getByRole("row").filter({ hasText: goldenCase.caseCode });
    await expect(refreshedRow.getByText("Passed", { exact: true })).toBeVisible({ timeout: 15_000 });
    await expect(
      refreshedRow.getByRole("button").filter({ hasText: "Run" })
    ).toBeEnabled({ timeout: 15_000 });
  }

  await installBrowserSession(page, counselor);
  await page.goto(`/scale-publication?scaleId=${scaleId}`);
  const counselorGoldenCasesTable = page.locator(".ant-card").filter({
    has: page.locator(".ant-card-head-title").getByText("Golden Case evidence", { exact: true })
  }).getByRole("table").first();
  for (const goldenCase of cases) {
    const row = counselorGoldenCasesTable.getByRole("row").filter({ hasText: goldenCase.caseCode });
    await row.getByRole("button", { name: "Approve case", exact: true }).click();
    const refreshedRow = counselorGoldenCasesTable.getByRole("row").filter({ hasText: goldenCase.caseCode });
    await expect(refreshedRow.getByText("Approved", { exact: true })).toBeVisible({ timeout: 15_000 });
  }
  await page.getByRole("button", { name: "Professional review", exact: true }).click();
  const professionalDialog = page.getByRole("dialog", { name: "Professional review" });
  await professionalDialog.getByLabel("Comment").fill("Independent technical E2E professional-role review; not a clinical endorsement.");
  await professionalDialog.getByRole("button", { name: "OK", exact: true }).click();
  await expect(page.getByText("COUNSELOR #", { exact: false }).first()).toBeVisible();

  await installBrowserSession(page, assessor);
  await page.goto(`/scale-publication?scaleId=${scaleId}`);
  await page.getByRole("button", { name: "Business review", exact: true }).click();
  const businessDialog = page.getByRole("dialog", { name: "Business review" });
  await businessDialog.getByLabel("Comment").fill("Independent technical E2E business-role review for disposable automation only.");
  await businessDialog.getByRole("button", { name: "OK", exact: true }).click();
  await expect(page.getByText("This scale version satisfies the technical publication gate.")).toBeVisible();
  await page.getByRole("button", { name: "Publish current version", exact: true }).click();
  await expect(page.getByText("Scale version published.")).toBeVisible();

  const published = await expectOk<{ id: number; versionNo: string; status: string }>(
    await request.get(`/api/v1/scales/${scaleId}`, { headers: authHeaders(assessor) })
  );
  expect(published.status).toBe("PUBLISHED");

  const now = Date.now();
  const task = await expectOk<{ id: number; status: string }>(
    await request.post("/api/v1/tasks", {
      headers: authHeaders(assessor),
      data: {
        taskName: `E2E Governance Lock ${suffix}`,
        scaleId,
        taskMode: "INDIVIDUAL",
        anonymousFlag: false,
        allowSaveFlag: true,
        allowTimeoutSubmitFlag: false,
        allowRetakeFlag: false,
        startTime: new Date(now - 60_000).toISOString().slice(0, 19),
        endTime: new Date(now + 86_400_000).toISOString().slice(0, 19)
      }
    })
  );
  expect(task.status).toBe("DRAFT");

  const forbiddenMutation = await request.post(`/api/v1/scales/${scaleId}/questions/${reverseQuestion!.id}`, {
    headers: authHeaders(assessor),
    data: {
      dimensionId: reverseQuestion!.dimensionId,
      questionTitle: "Attempted mutation of a published question",
      requiredFlag: true,
      reverseScoreFlag: false,
      weightValue: 1,
      sortNo: reverseQuestion!.sortNo
    }
  });
  expect(forbiddenMutation.status()).toBe(400);
  expect((await forbiddenMutation.json() as ApiEnvelope<null>).code).toBe("SCALE_NOT_DRAFT");

  const nextVersion = await expectOk<{ id: number }>(
    await request.post(`/api/v1/scales/${scaleId}/versions`, {
      headers: authHeaders(systemAdmin),
      data: {
        versionNo: `next-${suffix}`,
        scaleName: `E2E Governance Later Draft ${suffix}`,
        description: "Later draft used only to prove that the task remains locked to the published version."
      }
    })
  );
  expect(nextVersion.id).not.toBe(scaleId);
  const taskDetail = await expectOk<{ scaleId: number; scaleVersionNo: string }>(
    await request.get(`/api/v1/tasks/${task.id}`, { headers: authHeaders(assessor) })
  );
  expect(taskDetail.scaleId).toBe(scaleId);
  expect(taskDetail.scaleVersionNo).toBe(version.versionNo);

  const nextPackage = await expectOk<ScalePackage>(
    await request.get(`/api/v1/scales/${nextVersion.id}/package`, { headers: authHeaders(systemAdmin) })
  );
  const approveNextPackage = await request.put(`/api/v1/scales/${nextVersion.id}/package`, {
    headers: authHeaders(systemAdmin),
    data: approvedPackagePayload(nextPackage)
  });
  expect(approveNextPackage.status(), await approveNextPackage.text()).toBe(200);

  const staleCases = buildGoldenCases(`STALE_${suffix}`);
  const staleCaseIds: number[] = [];
  for (const goldenCase of staleCases) {
    const saved = await expectOk<{ id: number }>(
      await request.post(`/api/v1/scales/${nextVersion.id}/publication/golden-cases`, {
        headers: authHeaders(systemAdmin),
        data: {
          ...goldenCase,
          sourceReference: "Repository-owned stale-evidence fixture; no clinical meaning."
        }
      })
    );
    staleCaseIds.push(saved.id);
    await expectOk<Record<string, unknown>>(
      await request.post(`/api/v1/scales/${nextVersion.id}/publication/golden-cases/${saved.id}/run`, {
        headers: authHeaders(systemAdmin)
      })
    );
    await expectOk<Record<string, unknown>>(
      await request.post(`/api/v1/scales/${nextVersion.id}/publication/golden-cases/${saved.id}/approve`, {
        headers: authHeaders(counselor)
      })
    );
  }
  expect(staleCaseIds).toHaveLength(6);

  await expectOk<Record<string, unknown>>(
    await request.post(`/api/v1/scales/${nextVersion.id}/publication/reviews/PROFESSIONAL`, {
      headers: authHeaders(counselor),
      data: {
        decision: "APPROVED",
        reviewToken: `stale-professional-${suffix}`,
        comment: "Synthetic evidence before a deliberate content change; no clinical endorsement."
      }
    })
  );
  await expectOk<Record<string, unknown>>(
    await request.post(`/api/v1/scales/${nextVersion.id}/publication/reviews/BUSINESS`, {
      headers: authHeaders(assessor),
      data: {
        decision: "APPROVED",
        reviewToken: `stale-business-${suffix}`,
        comment: "Synthetic business evidence before a deliberate content change."
      }
    })
  );
  const readyBeforeChange = await expectOk<{ ready: boolean }>(
    await request.get(`/api/v1/scales/${nextVersion.id}/publication/readiness`, { headers: authHeaders(systemAdmin) })
  );
  expect(readyBeforeChange.ready).toBe(true);

  const nextDetail = await expectOk<ScaleDetail>(
    await request.get(`/api/v1/scales/${nextVersion.id}`, { headers: authHeaders(systemAdmin) })
  );
  const changedQuestion = nextDetail.questions.find((question) => question.questionNo === 1);
  expect(changedQuestion).toBeDefined();
  await expectOk<ScaleDetail>(
    await request.post(`/api/v1/scales/${nextVersion.id}/questions/${changedQuestion!.id}`, {
      headers: authHeaders(systemAdmin),
      data: {
        dimensionId: changedQuestion!.dimensionId,
        questionTitle: `${changedQuestion!.questionTitle} [content changed]`,
        requiredFlag: changedQuestion!.requiredFlag,
        reverseScoreFlag: changedQuestion!.reverseScoreFlag,
        weightValue: changedQuestion!.weightValue,
        sortNo: changedQuestion!.sortNo
      }
    })
  );
  const staleReadiness = await expectOk<{
    ready: boolean;
    cases: Array<{ caseCode: string; currentContent: boolean; latestRunPassed: boolean; approved: boolean }>;
    professionalReview?: unknown | null;
    businessReview?: unknown | null;
    blockers: string[];
  }>(
    await request.get(`/api/v1/scales/${nextVersion.id}/publication/readiness`, { headers: authHeaders(systemAdmin) })
  );
  expect(staleReadiness.ready).toBe(false);
  expect(staleReadiness.cases).toHaveLength(6);
  expect(staleReadiness.cases.every((goldenCase) => !goldenCase.currentContent)).toBe(true);
  expect(staleReadiness.professionalReview).toBeNull();
  expect(staleReadiness.businessReview).toBeNull();
  expect(staleReadiness.blockers.filter((blocker) => blocker.startsWith("GOLDEN_CASE_STALE:"))).toHaveLength(6);
  expect(staleReadiness.blockers).toContain("REVIEW_PROFESSIONAL_MISSING");
  expect(staleReadiness.blockers).toContain("REVIEW_BUSINESS_MISSING");

  await installBrowserSession(page, systemAdmin);
  await page.goto(`/scale-publication?scaleId=${nextVersion.id}`);
  await expect(page.getByText(
    `Golden Case ${staleCases[0].caseCode} targets earlier scale content. Create a new revision, rerun it, and obtain new approval.`
  )).toBeVisible();
  await expect(page.getByText("The current release fingerprint has no valid professional review.")).toBeVisible();
  await expect(page.getByText("The current release fingerprint has no valid business review.")).toBeVisible();
  await page.locator(".ant-select-selection-item").filter({ hasText: "English" }).click();
  await page.locator(".ant-select-item-option").filter({ hasText: "日本語" }).click();
  await expect(page.getByText(
    `Golden Case ${staleCases[0].caseCode} は以前の尺度内容に基づいています。新しいリビジョンを作成し、再実行・再承認してください。`
  )).toBeVisible();
  expect(consoleErrors).toEqual([]);
});
